"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "Kanjis",
      [
        {
          id: "19f6c1ed-7b9d-43ba-9c2a-9e04b1c56b9f",
          character: "合",
          level: "N4",
          meaning: "Hợp",
          chinaMeaning: "HỢP",
          mnemonic: "Người có 1 cái miệng là Hợp lý",
          onReading: "ゴウ、ガッ、カッ",
          kunReading: "あ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "25d46b4a-2484-4569-8244-a5ac7dd917bc",
          character: "日",
          level: "N5",
          meaning: "Mặt trời",
          chinaMeaning: "NHẬT",
          mnemonic: "Ngày qua ngày (日), mặt trời vẫn luôn chiếu sáng",
          onReading: "ニチ、二、ジツ",
          kunReading: "ひ、び、か",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "2c5dca1f-37b2-465e-8c07-4015e96838c7",
          character: "急",
          level: "N4",
          meaning: "Khẩn cấp",
          chinaMeaning: "CẤP",
          mnemonic: "Bị đâm \"Yo\" tim nên phải cấp cứu",
          onReading: "キュウ",
          kunReading: "いそ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "2c9107d9-00e7-4140-8836-1598cf7ae9bb",
          character: "六",
          level: "N5",
          meaning: "Sáu",
          chinaMeaning: "LỤC",
          mnemonic: null,
          onReading: "ロク、リク",
          kunReading: "む、むっ、むい",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "3400c170-b401-4be2-94fe-cfe29258fbac",
          character: "一",
          level: "N5",
          meaning: "Một",
          chinaMeaning: "NHẤT",
          mnemonic: "Được biểu diễn bằng một ngón tay",
          onReading: "イチ、 イツ",
          kunReading: "ひと",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "3bdf3e32-54c7-4942-8f66-6aa473fba3b2",
          character: "二",
          level: "N5",
          meaning: "Hai",
          chinaMeaning: "NHỊ",
          mnemonic: "Được biểu diễn bằng 2 ngón tay",
          onReading: "ニ、  ジ",
          kunReading: "ふた",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "3c839d9d-1733-4f6e-ab33-d1d385ab89a1",
          character: "名",
          level: "N5",
          meaning: "Tên",
          chinaMeaning: "DANH",
          mnemonic: "miệng 口 hô lớn từ ta タ để cho thiên hạ biết Ta là ai.",
          onReading: "メイ",
          kunReading: "な",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "3f9b4780-a882-49a5-b1ac-923250d5ac5f",
          character: "速",
          level: "N4",
          meaning: "Nhanh chóng",
          chinaMeaning: "TỐC",
          mnemonic: "Trên đường cao Tốc thì phải thúc 束chạy thật nhanh",
          onReading: "ソク",
          kunReading: "はや",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "44365825-ca03-47bf-888e-2ae8179cf462",
          character: "人",
          level: "N5",
          meaning: "Con người",
          chinaMeaning: "NHÂN",
          mnemonic: "Con người đứng bằng hai chân",
          onReading: "ジン、ジン",
          kunReading: "ひと",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "48d04a50-f0b2-4efb-a4d2-f3fc03c95cff",
          character: "紙",
          level: "N4",
          meaning: "Giấy",
          chinaMeaning: "CHỈ",
          mnemonic: "Viết họ tên 氏 lên tờ GIẤY mỏng như sợi chỉ 糸",
          onReading: "シ",
          kunReading: "かみ、がみ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "57b71851-43d8-4585-bc85-a68fcdbea3d8",
          character: "十",
          level: "N5",
          meaning: "Mười",
          chinaMeaning: "THẬP",
          mnemonic: "Giống hình ảnh bó 10 que lại với nhau",
          onReading: "ジュウ、ジッ、ジュッ",
          kunReading: "とお、と",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "57c71983-5b2f-4616-88d9-06a12105a417",
          character: "四",
          level: "N5",
          meaning: "Bốn",
          chinaMeaning: "TỨ",
          mnemonic: "Một hình chữ nhật có bốn góc",
          onReading: "シ",
          kunReading: "よ、よっ、よん",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "58911659-b38c-482a-8664-557ab5bd5d41",
          character: "都",
          level: "N4",
          meaning: "Kinh đô",
          chinaMeaning: "ĐÔ",
          mnemonic: "Kinh ĐÔ là nơi tập chung nhiều HỌC GIẢ",
          onReading: "ト、ツ",
          kunReading: "みやこ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "7b98b7e8-b881-493e-9b7c-f1306a0a3271",
          character: "直",
          level: "N4",
          meaning: "Thẳng",
          chinaMeaning: "TRỰC",
          mnemonic: "10 Con MẮT hướng vào xem livestream Trực Tiếp",
          onReading: "ジキ、チョク",
          kunReading: "なお、ただ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "877ebe02-9530-4e6e-8739-8bfedcb4b16b",
          character: "七",
          level: "N5",
          meaning: "Bảy",
          chinaMeaning: "THẤT",
          mnemonic: null,
          onReading: "シチ",
          kunReading: "なな、なの",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "8e50fbf1-741c-4a71-a1ef-1c87713807ac",
          character: "九",
          level: "N5",
          meaning: "Chín",
          chinaMeaning: "CỬU",
          mnemonic: null,
          onReading: "キュウ、ク",
          kunReading: "ここの",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "a0cb23bc-b50f-461c-8507-c6b2db738033",
          character: "八",
          level: "N5",
          meaning: "Tám",
          chinaMeaning: "BÁT",
          mnemonic: null,
          onReading: "ハチ",
          kunReading: "や、やっ、よう",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "a37530cc-c97b-43ab-b5c3-bff2a3b05a53",
          character: "三",
          level: "N5",
          meaning: "Ba",
          chinaMeaning: "TAM",
          mnemonic: "Được biểu diễn bằng ba ngón tay",
          onReading: "サン",
          kunReading: "み、みっ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "af08c07d-af8c-4e2f-b438-d4d196538749",
          character: "悪",
          level: "N4",
          meaning: "Ác",
          chinaMeaning: "ÁC",
          mnemonic: "Kẻ Ác trong Tay luôn giữ nhiều tòa nhà cao ốc",
          onReading: "アク",
          kunReading: "わる",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "d1bf2b7e-502e-4b1d-a66e-cbc9b37b7f40",
          character: "本",
          level: "N5",
          meaning: "Gốc",
          chinaMeaning: "BẢN, BỔN",
          mnemonic: "cái Cây (木) bị gạch ở dưới => chỗ đó là GỐC cây (本 BẢN)",
          onReading: "ホン",
          kunReading: "もと",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "df586e1f-a5df-4a65-af5e-b60bdc385d36",
          character: "方",
          level: "N5",
          meaning: "Phía, Hình vuông",
          chinaMeaning: "PHƯƠNG",
          mnemonic: "Vạn(万) cái đầu(亠) đều hướng về một phương(方)",
          onReading: "ホウ",
          kunReading: "かた、がた",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "e64bbe8e-fb28-4e3e-9a38-53aff0354270",
          character: "五",
          level: "N5",
          meaning: "Năm",
          chinaMeaning: "NGŨ",
          mnemonic: "Có thể làm chữ kanji với 5 que diêm không",
          onReading: "ゴ",
          kunReading: "いつ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "f307400c-6904-4efe-835c-e6fb424f476a",
          character: "去",
          level: "N4",
          meaning: "Đi, Đã qua",
          chinaMeaning: "KHỨ",
          mnemonic: "Quá KHỨ 去 riêng tư 厶 thì nên trôn sâu xuống đất 土",
          onReading: "カ、キョ",
          kunReading: "さ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },        
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
